version: "3.8"
services:
  python_echo:
    build: echo
    ports:
      - "9000:9000" # опционально, удобно для отладки
  pnginx:
    build: nginx
    depends_on: [python_echo]
    ports:
      - "8080:8080"
