version: "3.8"
services:
  echo:
    build: echo
    ports:
      - "9000:9000" # опционально, удобно для отладки
  nginx:
    build: nginx
    depends_on: [echo]
    environment:
      - MY_SERVER=http:\\localhost:9000
    ports:
      - "8080:8080"
